# Generated by Django 3.2.9 on 2021-12-25 07:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tournament', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='tdm',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50)),
                ('email', models.EmailField(max_length=254)),
                ('mobile_no', models.IntegerField(max_length=10)),
                ('pubg_id', models.IntegerField(max_length=10)),
                ('time', models.DateTimeField(auto_now_add=True)),
            ],
        ),
    ]
