# Generated by Django 3.2.9 on 2021-12-25 07:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tournament', '0002_tdm'),
    ]

    operations = [
        migrations.AlterField(
            model_name='tdm',
            name='mobile_no',
            field=models.IntegerField(),
        ),
        migrations.AlterField(
            model_name='tdm',
            name='pubg_id',
            field=models.IntegerField(),
        ),
    ]
